name: PantrLytics
version: 2026.01.06
url: https://github.com/Psychman52OS/PantrLytics
changelog: https://github.com/Psychman52OS/PantrLytics/blob/main/CHANGELOG.md
slug: pantrlytics
description: Inventory database with on-demand label generation and IPP printing
arch:
  - aarch64
  - amd64
  - armv7
startup: services
init: false
ingress: true
ingress_entry: /
panel_icon: mdi:barcode
hassio_api: true
homeassistant: "2024.1.0"

ports:
  "8099/tcp": null
ports_description:
  "8099/tcp": "HTTP port (set in add-on config)"

options:
  base_url: ""
  ipp_host: ""
  ipp_printer: ""
  serial_prefix: "USERconfigurable-"

schema:
  base_url: str?
  ipp_host: str?
  ipp_printer: str?
  serial_prefix: str?
